apiVersion: v1
kind: ConfigMap
metadata:
  name: api-config
  namespace: qtec-api
  labels:
    app: qtec-api
    component: config
data:
  LOG_LEVEL: "INFO"
  API_ENV: "kubernetes"
  REQUEST_TIMEOUT: "30"
